package simulator.util;

/**
 * Container for the control signals generated by the ControlUnit.
 * (Giữ nguyên hoặc điều chỉnh record từ code cũ của bạn)
 */
public record ControlSignals(
    boolean regWrite, boolean aluSrc, boolean memWrite, boolean memRead,
    boolean memToReg, boolean zeroBranch, boolean flagBranch, boolean uncondBranch,
    boolean reg2Loc, // Xem lại cần thiết không? Thường không có trong LEGv8 đơn giản
    boolean flagWrite // Chỉ thị ALU có cập nhật cờ không (cho lệnh xxxS)
) {
    public static ControlSignals NOP() {
        return new ControlSignals(false, false, false, false, false, false, false, false, false, false);
    }

    /*
     * Override toString() method to provide a string representation of the control signals.
     * This is useful for debugging and logging purposes.
     */
    @Override
    public String toString() {
        // Đảm bảo có đủ 10 đối số boolean cho 10 định dạng %b
        return String.format(
            "RegW:%b ALUSrc:%b MemW:%b MemR:%b MemToReg:%b ZeroB:%b FlagB:%b UncondB:%b Reg2Loc:%b FlagW:%b",
            regWrite,     // 1
            aluSrc,       // 2
            memWrite,     // 3
            memRead,      // 4
            memToReg,     // 5
            zeroBranch,   // 6
            flagBranch,   // 7
            uncondBranch, // 8
            reg2Loc,      // 9
            flagWrite     // 10
        );
    }
}